apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.1.2
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - nginx.local
            path: /grafana
          grafana.ini:
            server:
              domain: nginx.local
              root_url: "%(protocol)s://%(domain)s/grafana/"
              serve_from_sub_path: true

        prometheus:
          prometheusSpec:
            retention: 24h
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
